### ISSUE TITLE
Unable to list contents of /var/cache/salt/minion/files/base/_usr_share_java_jdk-8u112-linux-x64.tar.gz

### ISSUE THREAD

**Issue by porunov** [saltstack-formulas/sun-java-formula#21]
Hello, 

I can't install Java 8 properly with this formula.

Here is the failed state:

```
----------
          ID: unpack-jdk-tarball
    Function: archive.extracted
        Name: /usr/share/java
      Result: False
     Comment: Unable to list contents of /var/cache/salt/minion/files/base/_usr_share_java_jdk-8u112-linux-x64.tar.gz. If this is an XZ-compressed tar archive, install XZ Utils to enable listing its contents. If it is compressed using something other than XZ, it may be necessary to specify CLI options to decompress the archive. See the documentation for details. Additional info follows:          
                                                                                                                                     
              archive location:                                                                                                      
                  /var/cache/salt/minion/files/base/_usr_share_java_jdk-8u112-linux-x64.tar.gz                                       
                                                                                                                                     
              If the source archive is a tar archive compressed using a compression type not natively supported by the tar command, then setting the 'list_options' argument may allow the contents to be listed. Otherwise, if Salt is unable to determine the files/directories in the archive, the following workaround(s) would need to be used for this state to proceed (assuming the source file is a valid tar archive):                                                                                                                    
                                                                                                                                     
              - Ownership cannot be managed without setting 'enforce_ownership_on'.                                                  
     Started: 11:20:00.855186
    Duration: 300.165 ms
     Changes:   
    Warnings: The 'tar_options' argument has been deprecated, please use
              'options' instead.
----------
          ID: create-java-home
    Function: alternatives.install
        Name: java-home
      Result: False
     Comment: One or more requisite failed: sun-java.unpack-jdk-tarball
     Changes:   

```


Here is my pillar data:

```
java_home: /usr/lib/java
java:
  source_url: http://download.oracle.com/otn-pub/java/jdk/8u112-b15/jdk-8u112-linux-x64.tar.gz
  jce_url: http://download.oracle.com/otn-pub/java/jce/8/jce_policy-8.zip
  version_name: jdk-linux-server-x64-8u112
  prefix: /usr/share/java
  dl_opts: -L

# java:version_name is the name of the top-level directory inside the tarball
# java:prefix is where the tarball is unpacked into - prefix/version_name being
#             the location of the jdk
# java:dl_opts - cli args to cURL

```

What am I doing wrong?

Sincerely,
Alexandr
