### ISSUE TITLE
issues running formula

### ISSUE THREAD

**Issue by ppwd** [saltstack-formulas/sun-java-formula#34]
I was getting the following error running this updated formula.

Requisite declaration download-jdk-archive in SLS sun-java is not formed as a single key dictionary

changing the following block from
```
check-jdk-archive:
  module.run:
    - name: file.check_hash
    - path: {{ archive_file }}
    - file_hash: {{ java.source_hash }}
    - onchanges:
      - download-jdk-archive
    - require_in:
      - archive: unpack-jdk-archive
```
to

```
check-jdk-archive:
  module.run:
    - name: file.check_hash
    - path: {{ archive_file }}
    - file_hash: {{ java.source_hash }}
    - onchanges:
      - cmd: download-jdk-archive
    - require_in:
      - archive: unpack-jdk-archive
```

basically added the correct type of requisite (- cmd: download-jdk-archive)
