### ISSUE TITLE
Download retries pillar solution

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/sun-java-formula#48]
Sometimes download failure causes complete formula failure and headaches.
```
          ID: download-jdk-archive
    Function: cmd.run
        Name: curl -b oraclelicense=accept-securebackup-cookie -L -s -o '/usr/share/java/jdk-8u144-linux-x64.tar.gz' 'http://download.oracle.com/otn-pub/java/jdk/8u144-b01/090f390dda5b47b9b721c7dfaa008135/jdk-8u144-linux-x64.tar.gz'
      Result: False
     Comment: Command "curl -b oraclelicense=accept-securebackup-cookie -L -s -o '/usr/share/java/jdk-8u144-linux-x64.tar.gz' 'http://download.oracle.com/otn-pub/java/jdk/8u144-b01/090f390dda5b47b9b721c7dfaa008135/jdk-8u144-linux-x64.tar.gz'" run
     Started: 08:58:35.054559
    Duration: 1236334.473 ms
     Changes:  
              ----------
              pid:
                  7232
              retcode:
                  18             <====  PARTIAL DOWNLOAD COMPLETED
              stderr:
              stdout:
```
**Possible Solution**
The best solution is configuring retry via pillars.  Two approaches are possible.

1. Low level solution. Does this work?
```
pillar.example:

java:
  dl_opts: -b oraclelicense=accept-securebackup-cookie -L -s --connect-timeout 5  --max-time 10 --retry 5 --retry-delay 0 --retry-max-time 40
```

2. Salt retry option (https://docs.saltstack.com/en/latest/ref/states/requisites.html#retrying-states)
```
init.sls

    {% if grains['saltversioninfo'] >= [2017, 7, 0] %}
    - retry:
        attempts: {{ java.dl_retries }}
        interval: {{ java.dl_interval }}
    {% endif %}

pillar.example

java:
  ...
  dl_opts: -b oraclelicense=accept-securebackup-cookie -L -s
  dl_retries: 3
  dl_interval: 60
```
