### ISSUE TITLE
[BUG] sun-java.jce - archive_file is undefined

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/sun-java-formula#79]
### Formula commit hash / release tag

Master

### Versions reports (master & minion)
```
Salt Version:
           Salt: 3000
 
Dependency Versions:
           cffi: 1.13.2
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.3
        libgit2: 0.28.4
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.28.2
         Python: 3.7.7 (default, Mar 10 2020, 15:43:03)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 18.1.1
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 18.7.0
         system: Darwin
        version: 10.14.6 x86_64
```

### Pillar / config used
```
java:
  java_home: /usr/local/lib/java
  jre_lib_sec: /usr/local/lib/java/jre/lib/security/policy/
  uri: http://example.com/downloads/java/

  release: '8'
  major: '0'
  minor: '102'
  build: ''       #because we are not using oracle otn url
  dirhash: ''     #because we are not using oracle otn url

      {%- if grains.os == 'MacOS' %}
  source_url: http://example..com/downloads/java/jdk/8u102/jdk-8u102-macosx-x64.dmg
  source_hash: 'md5=9652fdf0b3387f1897369c7ec642f546'
      {%- elif grains.kernel == 'Linux' %}
  source_url: http://example.com/downloads/java/jdk/8u102/jdk-8u102-linux-x64.tar.gz
  source_hash: 'md5=bac58dcec9bb85859810a2a6acba740b'

  linux:
    #Increase priority for every version installed
    altpriority: {{ range(1, 9100000) | random }}
      {%- endif %}
  jce_url: http://download.oracle.com/otn-pub/java/jce/8/jce_policy-8.zip
  dl:
    retries: 2
    interval: 60
```

---

### Describe the bug

Getting error on MacOS-
```
[CRITICAL] Rendering SLS 'base:sun-java.jce' failed: Jinja variable 'archive_file' is undefined

```
### Attempts to fix the bug
I'm investigating now.
